### ISSUE TITLE
Overview table correct headers

### ISSUE THREAD

**Issue by patanj2** [patanj2/hpwhgen5_dashboard#9]
The table gets rendered once upon initial loading of the device tab and then secondly when items are selected on the graph.  A case that needs to be handled is where there are no elements selected on the graph

* Device table headers are currently hard coded
* Device table may be getting populated twice. once on overiew tab load and once on selection of locations on map

**Comment by RheemWeiyu** [comment]
- Device table headers are currently hard coded
       [WP] Need more discussion on this one
- Device table may be getting populated twice. once on overiew tab load and once on selection of locations on map
       [WP] Done
-   A case that needs to be handled is where there are no elements selected on the graph
       [WP] Currently, if user selects nothing, will return full data info
